apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: vibe-social
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
